import { GoogleTagManager } from "@next/third-parties/google";
import type React from "react";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const baseURL = "";

	return (
		<html lang="ja">
			<head>
				<title>蓮ノ空女学院 ウェブサイト</title>
				<meta
					name="description"
					content="石川県金沢市にある、私立蓮ノ空女学院のウェブサイトです。非公式によるエイプリルフール企画です。"
				/>
				<meta
					name="keywords"
					content="蓮ノ空女学院,ラブライブ,スクールアイドル,金沢市"
				/>
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href={`${baseURL}/favicon.ico`} />
				<meta property="og:title" content="蓮ノ空女学院 ウェブサイト" />
				<meta
					property="og:description"
					content="石川県金沢市にある、私立蓮ノ空女学院のウェブサイトです。非公式によるエイプリルフール企画です。"
				/>
				<meta property="og:type" content="website" />
				<meta property="og:url" content={baseURL} />
				<meta property="og:image" content={`${baseURL}/ogp_default.webp`} />
				<meta property="og:site_name" content="蓮ノ空女学院 ウェブサイト" />
				<meta name="twitter:card" content="summary_large_image" />
				<meta name="twitter:title" content="蓮ノ空女学院 ウェブサイト" />
				<meta
					name="twitter:description"
					content="石川県金沢市にある、私立蓮ノ空女学院のウェブサイトです。非公式によるエイプリルフール企画です。"
				/>
				<meta name="twitter:image" content={`${baseURL}/ogp_default.webp`} />
				<meta name="twitter:image:alt" content="蓮ノ空女学院 ウェブサイト" />
				<meta name="twitter:image:width" content="1200" />
				<meta name="twitter:image:height" content="630" />
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="anonymous"
				/>
				<link
					href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&family=Yuji+Syuku&display=swap"
					rel="stylesheet"
				/>
				<GoogleTagManager gtmId="xxx" />
			</head>
			<body>{children}</body>
		</html>
	);
}
